server:
  port: 8080

spring:
  application:
    # 应用名称
    name: ok-sba-client
  #arthas开关，可以在需要调式的时候开启，不需要的时候关闭
  arthas:
    enabled: true
  jmx:
    enabled: true
  boot:
    admin:
      client:
        # 服务端 url
        url: http://127.0.0.1:8888
        instance:
          # 客户端实例 url
          service-url: http://127.0.0.1:8080
          # 客户端实例名称
          name: ok-sba-client
        # 服务端配置密码后，此处必须配置服务端密码，否则注册不上
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        # 暴漏的接口 - 所有接口
        include: "*"

logging:
  file:
    name: client.log
  pattern:
    #     日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'


#arthas服务端域名
arthas:
  tunnel-server: ws://localhost:7777/ws
  #客户端id,应用名@随机值，js会截取前面的应用名
  agent-id: ${spring.application.name}_${random.value}
  #如果是防止一个机器上启动多个 arthas端口冲突。可以配置为随机端口(配置为0)，或者配置为 -1，并且通过tunnel server来使用arthas。
  telnet-port: -1
  http-port: -1
